## Question: Is there prejudice against Mental Health Issues at Work in the Tech Industry in the US?

##### Sub-Question 1: What is the picture by state?

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Data Reading

In [21]:
mental_raw = pd.read_csv('survey.csv')
mental_raw

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2015-09-12 11:17:21,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,...,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,NaN
1255,2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,26-100,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,NaN
1256,2015-11-07 12:36:58,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,NaN
1257,2015-11-30 21:25:06,46,f,United States,NC,No,No,No,NaN,100-500,...,Don't know,Yes,No,No,No,No,No,No,No,NaN
1258,2016-02-01 23:04:31,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,NaN

## NaN Cleaning

In [95]:
mental_raw.isna().sum()/len(mental)
mental_raw.loc[~(mental_raw.comments.isna()),'comments']
# 86% of comments column is NaN and is not structured so dropping it.

mental = mental_raw.drop('comments', axis = 1)
mental

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2015-09-12 11:17:21,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No
1255,2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,26-100,...,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No
1256,2015-11-07 12:36:58,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No
1257,2015-11-30 21:25:06,46,f,United States,NC,No,No,No,NaN,100-500,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No
1258,2016-02-01 23:04:31,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,...,Yes,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No

In [96]:
mental.isna().sum()

# Column state also has a lot of Nulls. From Kaggle doc this is:
# "If you live in the United States, which state or territory do you live in?"
# The column is only relevant for the US

# Will replace state outside the US for all as 'Not Defined'
# Will replace ones inside the US without state as "Not answered"

mental.loc[mental.Country != 'United States','state'] = 'Not Defined'
mental.loc[(mental.Country == 'United States') & (mental.state.isna()), 'state'] = 'Not Answered'
mental

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,2014-08-27 11:29:44,32,Male,Canada,Not Defined,NaN,No,No,Rarely,6-25,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,2014-08-27 11:29:46,31,Male,United Kingdom,Not Defined,NaN,Yes,Yes,Often,26-100,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2015-09-12 11:17:21,26,male,United Kingdom,Not Defined,No,No,Yes,NaN,26-100,...,Don't know,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No
1255,2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,26-100,...,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No
1256,2015-11-07 12:36:58,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No
1257,2015-11-30 21:25:06,46,f,United States,NC,No,No,No,NaN,100-500,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No
1258,2016-02-01 23:04:31,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,...,Yes,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No

In [97]:
mental.isna().sum()
# work interfere has 21% NaN, will replace with 'Not Answered'

mental.loc[mental.work_interfere.isna(),'work_interfere'] = 'Not Answered'
mental.work_interfere.value_counts()

#Self employed also with some NaN, will put 'Not Answered'
mental.loc[mental.self_employed.isna(),'self_employed'] = 'Not Answered'
mental.self_employed.value_counts()

No              1095
Yes              146
Not Answered      18
Name: self_employed, dtype: int64

## Further Cleaning - Column Values Verification and Normalization

In [103]:
# Change date to datetime and keep only date (remove time)
mental.dtypes
mental.Timestamp = pd.to_datetime (mental.Timestamp, errors = 'coerce')
mental.Timestamp = mental.Timestamp.dt.date

In [105]:
mental.dtypes

Timestamp                    object
Age                           int64
Gender                       object
Country                      object
state                        object
self_employed                object
family_history               object
treatment                    object
work_interfere               object
no_employees                 object
remote_work                  object
tech_company                 object
benefits                     object
care_options                 object
wellness_program             object
seek_help                    object
anonymity                    object
leave                        object
mental_health_consequence    object
phys_health_consequence      object
coworkers                    object
supervisor                   object
mental_health_interview      object
phys_health_interview        object
mental_vs_physical           object
obs_consequence              object
dtype: object

In [104]:
# Check all columns values

[(column, mental[column].unique()) for column in mental.columns]

[('Timestamp', array([datetime.date(2014, 8, 27), datetime.date(2014, 8, 28),
         datetime.date(2014, 8, 29), datetime.date(2014, 8, 30),
         datetime.date(2014, 8, 31), datetime.date(2014, 9, 1),
         datetime.date(2014, 9, 2), datetime.date(2014, 9, 3),
         datetime.date(2014, 9, 4), datetime.date(2014, 9, 5),
         datetime.date(2014, 9, 8), datetime.date(2014, 9, 9),
         datetime.date(2014, 9, 11), datetime.date(2014, 9, 12),
         datetime.date(2014, 9, 13), datetime.date(2014, 9, 14),
         datetime.date(2014, 9, 20), datetime.date(2014, 9, 23),
         datetime.date(2014, 9, 26), datetime.date(2014, 9, 30),
         datetime.date(2014, 10, 2), datetime.date(2014, 10, 5),
         datetime.date(2014, 10, 9), datetime.date(2014, 11, 5),
         datetime.date(2014, 11, 6), datetime.date(2014, 11, 16),
         datetime.date(2014, 12, 1), datetime.date(2014, 12, 15),
         datetime.date(2015, 1, 3), datetime.date(2015, 2, 21),
         datetime.date(2015, 2, 22), datetime.date(2015, 2, 24),
         datetime.date(2015, 2, 26), datetime.date(2015, 4, 2),
         datetime.date(2015, 4, 4), datetime.date(2015, 4, 6),
         datetime.date(2015, 4, 11), datetime.date(2015, 4, 23),
         datetime.date(2015, 5, 5), datetime.date(2015, 5, 6),
         datetime.date(2015, 5, 7), datetime.date(2015, 6, 25),
         datetime.date(2015, 7, 22), datetime.date(2015, 7, 27),
         datetime.date(2015, 8, 17), datetime.date(2015, 8, 20),
         datetime.date(2015, 8, 25), datetime.date(2015, 9, 12),
         datetime.date(2015, 9, 26), datetime.date(2015, 11, 7),
         datetime.date(2015, 11, 30), datetime.date(2016, 2, 1)],
        dtype=object)),
 ('Age',
  array([         37,          44,          32,          31,          33,
                  35,          39,          42,          23,          29,
                  36,          27,          46,          41,          34,
                  30,          40,          38,          50,          24,
                  18,          28,          26,          22,          19,
                  25,          45,          21,         -29,          43,
                  56,          60,          54,         329,          55,
         99999999999,          48,          20,          57,          58,
                  47,          62,          51,          65,          49,
               -1726,           5,          53,          61,           8,
                  11,          -1,          72])),
 ('Gender',
  array(['Female', 'M', 'Male', 'male', 'female', 'm', 'Male-ish', 'maile',
         'Trans-female', 'Cis Female', 'F', 'something kinda male?',
         'Cis Male', 'Woman', 'f', 'Mal', 'Male (CIS)', 'queer/she/they',
         'non-binary', 'Femake', 'woman', 'Make', 'Nah', 'All', 'Enby',
         'fluid', 'Genderqueer', 'Female ', 'Androgyne', 'Agender',
         'cis-female/femme', 'Guy (-ish) ^_^', 'male leaning androgynous',
         'Male ', 'Man', 'Trans woman', 'msle', 'Neuter', 'Female (trans)',
         'queer', 'Female (cis)', 'Mail', 'cis male', 'A little about you',
         'Malr', 'p', 'femail', 'Cis Man',
         'ostensibly male, unsure what that really means'], dtype=object)),
 ('Country',
  array(['United States', 'Canada', 'United Kingdom', 'Bulgaria', 'France',
         'Portugal', 'Netherlands', 'Switzerland', 'Poland', 'Australia',
         'Germany', 'Russia', 'Mexico', 'Brazil', 'Slovenia', 'Costa Rica',
         'Austria', 'Ireland', 'India', 'South Africa', 'Italy', 'Sweden',
         'Colombia', 'Latvia', 'Romania', 'Belgium', 'New Zealand',
         'Zimbabwe', 'Spain', 'Finland', 'Uruguay', 'Israel',
         'Bosnia and Herzegovina', 'Hungary', 'Singapore', 'Japan',
         'Nigeria', 'Croatia', 'Norway', 'Thailand', 'Denmark',
         'Bahamas, The', 'Greece', 'Moldova', 'Georgia', 'China',
         'Czech Republic', 'Philippines'], dtype=object)),
 ('state',
  array(['IL', 'IN', 'Not Defined', 'TX', 'TN', 'MI', 'OH', 'CA', 'CT',
         'MD', 'NY', 'NC', 'MA', 'IA', 'PA', 'WA', 'WI', 'UT',
         'Not Answered', 'NM', 'OR', 'FL', 'MN', 'MO', 'AZ', 'CO', 'GA',
         'DC', 'NE', 'WV', 'OK', 'KS', 'VA', 'NH', 'KY', 'AL', 'NV', 'NJ',
         'SC', 'VT', 'SD', 'ID', 'MS', 'RI', 'WY', 'LA', 'ME'], dtype=object)),
 ('self_employed', array(['Not Answered', 'Yes', 'No'], dtype=object)),
 ('family_history', array(['No', 'Yes'], dtype=object)),
 ('treatment', array(['Yes', 'No'], dtype=object)),
 ('work_interfere',
  array(['Often', 'Rarely', 'Never', 'Sometimes', 'Not Answered'],
        dtype=object)),
 ('no_employees',
  array(['6-25', 'More than 1000', '26-100', '100-500', '1-5', '500-1000'],
        dtype=object)),
 ('remote_work', array(['No', 'Yes'], dtype=object)),
 ('tech_company', array(['Yes', 'No'], dtype=object)),
 ('benefits', array(['Yes', "Don't know", 'No'], dtype=object)),
 ('care_options', array(['Not sure', 'No', 'Yes'], dtype=object)),
 ('wellness_program', array(['No', "Don't know", 'Yes'], dtype=object)),
 ('seek_help', array(['Yes', "Don't know", 'No'], dtype=object)),
 ('anonymity', array(['Yes', "Don't know", 'No'], dtype=object)),
 ('leave', array(['Somewhat easy', "Don't know", 'Somewhat difficult',
         'Very difficult', 'Very easy'], dtype=object)),
 ('mental_health_consequence', array(['No', 'Maybe', 'Yes'], dtype=object)),
 ('phys_health_consequence', array(['No', 'Yes', 'Maybe'], dtype=object)),
 ('coworkers', array(['Some of them', 'No', 'Yes'], dtype=object)),
 ('supervisor', array(['Yes', 'No', 'Some of them'], dtype=object)),
 ('mental_health_interview', array(['No', 'Yes', 'Maybe'], dtype=object)),
 ('phys_health_interview', array(['Maybe', 'No', 'Yes'], dtype=object)),
 ('mental_vs_physical', array(['Yes', "Don't know", 'No'], dtype=object)),
 ('obs_consequence', array(['No', 'Yes'], dtype=object))]

In [137]:
# Limit Age to 18 to 99. Other values considered out of range put =-1
mental.loc[(mental.Age > 99) |(mental.Age < 18) , 'Age'] = -1

In [154]:
#Normalize Gender column to male, female, other

mental.Gender = mental.Gender.str.lower().str.strip()
gender_conv = {'male':'m', 'woman':'f', 'make':'m', 'man':'m', 'malr':'m', 'femake':'f', 'maile':'m',\
              'msle':'m','cis male': 'm', 'cis female': 'f', 'female (cis)': 'f', 'male (cis)': 'm', 'female':'f',\
              'mal':'m', 'cis-female/femme':'f', 'femail': 'f', 'mail':'m'}

mental.replace({'Gender': gender_conv}, inplace = True)
mental.loc[(mental.Gender != 'm') & (mental.Gender != 'f'), 'Gender'] = 'other'
mental.Gender.value_counts()

m        989
f        247
other     23
Name: Gender, dtype: int64

In [156]:
#Our Main Analysis is done in the US, so will filter the data for US only

mental_US = mental[mental.Country=='United States']
mental_US

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,2014-08-27,37,f,United States,IL,Not Answered,No,Yes,Often,6-25,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,2014-08-27,44,m,United States,IN,Not Answered,No,No,Rarely,More than 1000,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
4,2014-08-27,31,m,United States,TX,Not Answered,No,No,Never,100-500,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No
5,2014-08-27,33,m,United States,TN,Not Answered,Yes,No,Sometimes,6-25,...,Don't know,Don't know,No,No,Yes,Yes,No,Maybe,Don't know,No
6,2014-08-27,35,f,United States,MI,Not Answered,Yes,Yes,Sometimes,1-5,...,No,Somewhat difficult,Maybe,Maybe,Some of them,No,No,No,Don't know,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1253,2015-08-25,36,m,United States,UT,No,Yes,No,Rarely,More than 1000,...,Don't know,Somewhat easy,Maybe,Maybe,Some of them,Some of them,No,No,Don't know,No
1255,2015-09-26,32,m,United States,IL,No,Yes,Yes,Often,26-100,...,Yes,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No
1256,2015-11-07,34,m,United States,CA,No,Yes,Yes,Sometimes,More than 1000,...,Don't know,Somewhat difficult,Yes,Yes,No,No,No,No,No,No
1257,2015-11-30,46,f,United States,NC,No,No,No,Not Answered,100-500,...,Don't know,Don't know,Yes,No,No,No,No,No,No,No
1258,2016-02-01,25,m,United States,IL,No,Yes,Yes,Sometimes,26-100,...,Yes,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No